import {render, screen, waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {MemoryRouter} from 'react-router-dom';
import {afterEach, expect, it, vi} from 'vitest';
import RelationPanel from '../src/features/spec/RelationPanel';
const item=(kind:string,id:string)=>({kind,itemId:id,title:id+' 원문',documentId:kind+'doc',path:'docs/'+kind+'.md',anchor:'actual-'+kind,line:9});
const view={snapshotId:'s1',sourceRevision:'abc',analysisVersion:1,analysisStatus:'partial',uncheckedReason:null,requirements:[{requirement:item('req','REQ-001'),designCoverage:'linked',designs:[item('ui','UI-001'),item('api','API-001')],tasks:[{item:item('task','TASK-001'),execution:{status:'done',issueNumber:7,pullRequests:[8],observedAt:'2026-10-02T00:00:00Z'}}]}],findings:[{code:'MISSING_REFERENCE',documentId:'uidoc',path:'docs/ui.md',line:10,message:'없는 정의',targetId:'API-999'}],totalElements:51,page:0,size:50};
function mock(data:unknown=view){vi.stubGlobal('fetch',vi.fn(()=>Promise.resolve(new Response(JSON.stringify(data)))));}
function open(snapshotId='s1'){return render(<MemoryRouter><RelationPanel projectId='p1' snapshotId={snapshotId} fullName='owner/repo'/></MemoryRouter>);}
afterEach(()=>vi.unstubAllGlobals());
it('pins all design/task sources and separates current execution observations',async()=>{mock();open();expect(await screen.findByText('부분 분석')).toBeVisible();for(const kind of ['req','ui','api','task'])expect(screen.getByRole('link',{name:kind.toUpperCase()+'-001 '+kind.toUpperCase()+'-001 원문'})).toHaveAttribute('href','/projects/p1/documents/'+kind+'doc?snapshotId=s1#actual-'+kind);expect(screen.getByText(/^· 관찰 /)).toBeVisible();expect(screen.getByText('MISSING_REFERENCE')).toBeVisible();await userEvent.click(screen.getByRole('button',{name:'설계 관계 다음'}));await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining('page=1'),expect.anything()));});
it('legacy and no design definitions never assert fulfillment or not-applicable',async()=>{mock({...view,analysisStatus:'unchecked',uncheckedReason:'NOT_COMPUTED',requirements:[],findings:[],totalElements:0});open();expect(await screen.findByText('미분석')).toBeVisible();expect(screen.getByText(/새 수집/)).toBeVisible();});
it('discards old snapshot responses after switching snapshots',async()=>{let release:(r:Response)=>void=()=>{};vi.stubGlobal('fetch',vi.fn((url:string)=>String(url).includes('snapshotId=s1')?new Promise<Response>(r=>{release=r;}):Promise.resolve(new Response(JSON.stringify({...view,snapshotId:'s2',sourceRevision:'NEW'})))));const {rerender}=open();rerender(<MemoryRouter><RelationPanel projectId='p1' snapshotId='s2' fullName='owner/repo'/></MemoryRouter>);expect(await screen.findByText('NEW')).toBeVisible();release(new Response(JSON.stringify(view)));await waitFor(()=>expect(screen.queryByText('abc')).not.toBeInTheDocument());});
