import {render,screen,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {MemoryRouter,Routes,Route,useNavigate} from 'react-router-dom';
import {afterEach,expect,it,vi} from 'vitest';
import TaskContextPage from '../src/features/spec/TaskContextPage';
import TaskRows from '../src/features/dashboard/TaskRows';
const project={id:'p1',fullName:'owner/repo',branch:'main',docsRoot:'docs',currentSnapshotId:'s1',version:1,syncState:'succeeded',manageable:false};
const item={kind:'task',itemId:'TASK-001',title:'구현',documentId:'taskdoc',path:'docs/task.md',anchor:'actual-task',line:9};
const view={snapshotId:'s1',sourceRevision:'pinned123',branch:'main',docsRoot:'docs',schemaVersion:1,state:'partial',reason:null,task:{item,fields:{검증:'`gradle test`'},truncated:false,warnings:[]},relatedRequirements:[],designs:[],dependencies:[],documents:[{documentId:'taskdoc',path:'docs/task.md',title:'작업',documentUrl:'/projects/p1/documents/taskdoc?snapshotId=s1',sourceUrl:'https://github.com/owner/repo/blob/pinned123/docs/task.md',sourceHash:'hash'}],rules:[{path:'AGENTS.md',available:false,sourceHash:null,sourceUrl:'https://github.com/owner/repo/blob/pinned123/AGENTS.md'}],execution:{status:'done',issueNumber:7,observedAt:'2026-10-02T00:00:00Z'},findings:[],checklistStatus:'pass',markdown:'# 참고 자료\n기준 pinned123\n`gradle test`'};
function mock(data:unknown=view){vi.stubGlobal('fetch',vi.fn((url:string)=>Promise.resolve(new Response(JSON.stringify(String(url).includes('/context')?data:String(url).includes('/documents')?{snapshotId:'s1',items:[],nextCursor:null}:project)))));}
function open(query='?snapshotId=s1'){return render(<MemoryRouter initialEntries={['/projects/p1/tasks/TASK-001/context'+query]}><Routes><Route path='/projects/:projectId/tasks/:taskId/context' element={<TaskContextPage/>}/></Routes></MemoryRouter>);}
afterEach(()=>vi.unstubAllGlobals());
it('task table context entry pins the source snapshot',()=>{render(<MemoryRouter><TaskRows projectId='p1' snapshotId='s1' tasks={[{taskSpecId:'TASK-001',title:'작업',documentId:'doc',anchor:'actual-task',status:'done',issueNumber:7,issueTitle:'작업',assignees:[],pullRequests:[],mappingConflict:false,observedAt:null}]}/></MemoryRouter>);expect(screen.getByRole('link',{name:'컨텍스트'})).toHaveAttribute('href','/projects/p1/tasks/TASK-001/context?snapshotId=s1');expect(screen.getByRole('link',{name:'작업'})).toHaveAttribute('href','/projects/p1/documents/doc?snapshotId=s1#actual-task');});
it('pins source context and copies only selected snapshot Markdown',async()=>{mock();const clipboard={writeText:vi.fn(()=>Promise.resolve())};Object.defineProperty(navigator,'clipboard',{value:clipboard,configurable:true});open();expect(await screen.findByRole('textbox',{name:'컨텍스트 Markdown'})).toHaveValue(view.markdown);expect(screen.getByText('부분 구성')).toBeVisible();expect(screen.getByRole('link',{name:'작업 원문'})).toHaveAttribute('href','/projects/p1/documents/taskdoc?snapshotId=s1#actual-task');expect(screen.getByText(/규칙 자료 미확인/)).toBeVisible();await userEvent.click(screen.getByRole('button',{name:'컨텍스트 복사'}));expect(clipboard.writeText).toHaveBeenCalledWith(view.markdown);expect(await screen.findByText('복사했습니다.')).toBeVisible();});
it('does not offer complete context for legacy metadata',async()=>{mock({...view,state:'unchecked',reason:'NOT_COMPUTED',task:null,documents:[],rules:[],markdown:'미확인'});open();expect(await screen.findByText('미확인')).toBeVisible();expect(screen.queryByRole('button',{name:'컨텍스트 복사'})).not.toBeInTheDocument();});
it.each([[400,'ID'],[404,'권한'],[409,'중복'],[410,'게시본']])('distinguishes context HTTP%s',async(status,text)=>{mock();const original=vi.mocked(fetch).getMockImplementation()!;vi.mocked(fetch).mockImplementation((u,...args)=>String(u).includes('/context')?Promise.resolve(new Response(JSON.stringify({code:'TEST'}),{status:Number(status)})):original(u,...args));open();expect(await screen.findByRole('alert')).toHaveTextContent(String(text));});
it('rejects a response for a different selected snapshot',async()=>{mock({...view,snapshotId:'wrong'});open();expect(await screen.findByRole('alert')).toHaveTextContent('조회 기준');await waitFor(()=>expect(screen.queryByDisplayValue(view.markdown)).not.toBeInTheDocument());});
it('keeps the newer snapshot when the earlier request resolves late',async()=>{
 mock();const original=vi.mocked(fetch).getMockImplementation()!;let release:(r:Response)=>void=()=>{};
 vi.mocked(fetch).mockImplementation((u,...args)=>String(u).includes('/context?snapshotId=s1')?new Promise<Response>(r=>{release=r;}):String(u).includes('/context?snapshotId=s2')?Promise.resolve(new Response(JSON.stringify({...view,snapshotId:'s2',sourceRevision:'NEW_CTX',markdown:'NEW MARKDOWN'}))):original(u,...args));
 function Change(){const nav=useNavigate();return <button onClick={()=>nav('/projects/p1/tasks/TASK-001/context?snapshotId=s2')}>게시본 전환</button>;}
 render(<MemoryRouter initialEntries={['/projects/p1/tasks/TASK-001/context?snapshotId=s1']}><Change/><Routes><Route path='/projects/:projectId/tasks/:taskId/context' element={<TaskContextPage/>}/></Routes></MemoryRouter>);
 await userEvent.click(screen.getByRole('button',{name:'게시본 전환'}));expect(await screen.findByRole('textbox',{name:'컨텍스트 Markdown'})).toHaveValue('NEW MARKDOWN');release(new Response(JSON.stringify(view)));await waitFor(()=>expect(screen.queryByText('pinned123')).not.toBeInTheDocument());
});
it('reports a clipboard failure without claiming a successful copy',async()=>{mock();Object.defineProperty(navigator,'clipboard',{value:{writeText:vi.fn(()=>Promise.reject(new Error('unavailable')))},configurable:true});open();await screen.findByRole('textbox',{name:'컨텍스트 Markdown'});await userEvent.click(screen.getByRole('button',{name:'컨텍스트 복사'}));expect(await screen.findByText(/복사하지 못했습니다/)).toBeVisible();expect(screen.queryByText('복사했습니다.')).not.toBeInTheDocument();});
it('shows observed linked pull requests with the current Issue boundary',async()=>{mock({...view,execution:{...view.execution,pullRequests:[81,82]}});open();expect(await screen.findByRole('link',{name:'PR#81'})).toHaveAttribute('href','https://github.com/owner/repo/pull/81');expect(screen.getByRole('link',{name:'PR#82'})).toHaveAttribute('href','https://github.com/owner/repo/pull/82');});
